// prisma/seedPlantTypes.ts
import { PrismaClient } from '@prisma/client';

export async function seedPlantTypes(prisma: PrismaClient): Promise<void> {
  const plantTypes = [
    {
      name: 'Cây Lưỡi hổ',
      scientificName: 'Sansevieria trifasciata',
      family: 'Asparagaceae',
      description: 'Cây cảnh lá xanh đậm viền vàng cứng cáp, rất dễ trồng và giúp thanh lọc không khí trong nhà.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Nhân giống',
            order: 1,
            duration: 42,
            description: 'Nhân giống bằng cách tách bụi hoặc giâm lá trong đất ẩm để ra rễ mới.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 40,
            optimalHumidityMax: 70,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 0,
            optimalLightMax: 3,
            lightRequirement: 'Ánh sáng gián tiếp hoặc bóng râm',
            waterRequirement: 'Thấp (chỉ tưới khi đất khô)',
            nutrientRequirement: 'Thấp (bón phân loãng 2–3 tháng/lần)',
            careInstructions: 'Tránh để nước đọng trên lá; có thể trồng nơi ít ánh sáng',
            pestSusceptibility: 'Ít sâu bệnh, đôi khi bị rệp sáp'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 365,
            description: 'Cây bén rễ và mọc lá mới, đẻ nhánh con.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 30,
            optimalHumidityMax: 70,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 0,
            optimalLightMax: 3,
            lightRequirement: 'Ánh sáng yếu hoặc bóng râm',
            waterRequirement: 'Thấp (tưới rất ít)',
            nutrientRequirement: 'Thấp (bón phân hữu cơ loãng 3–4 tháng/lần)',
            careInstructions: 'Thay chậu 2–3 năm/lần; lau bụi lá',
            pestSusceptibility: 'Thối rễ nếu úng'
          },
          {
            stageName: 'Trưởng thành',
            order: 3,
            duration: 365,
            description: 'Cây đạt kích thước tối đa, lá dày cứng, hiếm khi ra hoa.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 30,
            optimalHumidityMax: 70,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 0,
            optimalLightMax: 3,
            lightRequirement: 'Sống tốt trong phòng thiếu sáng',
            waterRequirement: 'Thấp (tưới 2–4 tuần/lần)',
            nutrientRequirement: 'Thấp (bón phân chậm tan 6 tháng/lần)',
            careInstructions: 'Cắt bỏ lá vàng úa',
            pestSusceptibility: 'Ít sâu bệnh'
          }
        ]
      }
    },
    {
      name: 'Cây Trầu bà',
      scientificName: 'Epipremnum aureum',
      family: 'Araceae',
      description: 'Cây dây leo lá tim vàng xanh, dễ trồng trong nước hoặc đất, thường trồng trang trí và lọc không khí.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Nhân giống',
            order: 1,
            duration: 21,
            description: 'Cắt đoạn thân có rễ khí, giâm vào nước hoặc đất ẩm để ra rễ mới.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 5.5,
            optimalPHMax: 7.5,
            optimalLightMin: 0,
            optimalLightMax: 2,
            lightRequirement: 'Ánh sáng yếu đến trung bình',
            waterRequirement: 'Trung bình (giữ ẩm đất)',
            nutrientRequirement: 'Thấp (bón phân loãng mỗi 2 tháng)',
            careInstructions: 'Thay nước nếu trồng thủy sinh; cắt tỉa nhánh dài',
            pestSusceptibility: 'Có thể bị rệp sáp'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 365,
            description: 'Cây ra lá đều đặn, dây leo dài thêm.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 34,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 5.5,
            optimalPHMax: 7.5,
            optimalLightMin: 0,
            optimalLightMax: 2,
            lightRequirement: 'Ánh sáng gián tiếp',
            waterRequirement: 'Trung bình (tưới khi đất se khô)',
            nutrientRequirement: 'Thấp (bón hữu cơ 3–4 tháng/lần)',
            careInstructions: 'Lau lá, xoay chậu nhận sáng đều',
            pestSusceptibility: 'Thối rễ nếu quá ẩm'
          },
          {
            stageName: 'Trưởng thành',
            order: 3,
            duration: 365,
            description: 'Dây leo dài đến vài mét, lá to hơn khi đủ nắng.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 34,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 5.5,
            optimalPHMax: 7.5,
            optimalLightMin: 0,
            optimalLightMax: 2,
            lightRequirement: 'Sáng nhẹ, tránh nắng gắt',
            waterRequirement: 'Trung bình (1–2 lần/tuần)',
            nutrientRequirement: 'Thấp (bón chậm tan 6 tháng/lần)',
            careInstructions: 'Cắt tỉa dây để rậm lá',
            pestSusceptibility: 'Rệp sáp'
          }
        ]
      }
    },
    {
      name: 'Cây Lan ý',
      scientificName: 'Spathiphyllum wallisii',
      family: 'Araceae',
      description: 'Cây lá xanh thẫm, hoa trắng hình mo, ưa bóng mát và lọc không khí.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Nhân giống',
            order: 1,
            duration: 24,
            description: 'Tách bụi cây con từ khóm mẹ và trồng sang chậu mới.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 60,
            optimalHumidityMax: 90,
            optimalPHMin: 5.5,
            optimalPHMax: 7.0,
            optimalLightMin: 0,
            optimalLightMax: 1,
            lightRequirement: 'Bóng râm hoặc ánh sáng yếu',
            waterRequirement: 'Cao (đất luôn ẩm)',
            nutrientRequirement: 'Trung bình (bón hàng tháng để ra hoa)',
            careInstructions: 'Phun sương lên lá; tránh nắng trực tiếp',
            pestSusceptibility: 'Nhện đỏ, rệp sáp'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 365,
            description: 'Cây phát triển nhiều lá mới, chuẩn bị ra hoa.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 60,
            optimalHumidityMax: 90,
            optimalPHMin: 5.5,
            optimalPHMax: 7.0,
            optimalLightMin: 0,
            optimalLightMax: 1,
            lightRequirement: 'Ánh sáng khuếch tán',
            waterRequirement: 'Cao (2–3 lần/tuần)',
            nutrientRequirement: 'Trung bình (NPK loãng mỗi tháng)',
            careInstructions: 'Lau lá; giữ ẩm không khí cao',
            pestSusceptibility: 'Thối rễ nếu úng'
          },
          {
            stageName: 'Ra hoa',
            order: 3,
            duration: 21,
            description: 'Cây trổ mo hoa trắng bền khoảng vài tuần.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 60,
            optimalHumidityMax: 90,
            optimalPHMin: 5.5,
            optimalPHMax: 7.0,
            optimalLightMin: 0,
            optimalLightMax: 1,
            lightRequirement: 'Ánh sáng yếu đến trung bình',
            waterRequirement: 'Cao (duy trì ẩm)',
            nutrientRequirement: 'Trung bình (bón nhiều kali trước hoa)',
            careInstructions: 'Không di chuyển khi ra hoa',
            pestSusceptibility: 'Nấm đốm lá'
          }
        ]
      }
    },
    {
      name: 'Cây Kim tiền',
      scientificName: 'Zamioculcas zamiifolia',
      family: 'Araceae',
      description: 'Cây thân rễ củ, lá dày xanh bóng, dễ sống trong điều kiện thiếu sáng.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Nhân giống',
            order: 1,
            duration: 35,
            description: 'Tách củ hoặc giâm lá trong đất ẩm để mọc củ mới.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 30,
            optimalHumidityMax: 70,
            optimalPHMin: 6.0,
            optimalPHMax: 7.0,
            optimalLightMin: 0,
            optimalLightMax: 2,
            lightRequirement: 'Bóng râm hoặc ánh sáng gián tiếp',
            waterRequirement: 'Thấp (để đất khô mới tưới)',
            nutrientRequirement: 'Thấp (bón chậm tan mỗi 6 tháng)',
            careInstructions: 'Lau bụi lá; tránh úng',
            pestSusceptibility: 'Ít sâu bệnh'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 365,
            description: 'Cây ra chồi mới từ củ, phát triển cành lá.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 30,
            optimalHumidityMax: 70,
            optimalPHMin: 6.0,
            optimalPHMax: 7.0,
            optimalLightMin: 0,
            optimalLightMax: 2,
            lightRequirement: 'Ánh sáng yếu vẫn sinh trưởng',
            waterRequirement: 'Thấp (1–2 lần/tháng)',
            nutrientRequirement: 'Thấp (bón chậm tan 6 tháng/lần)',
            careInstructions: 'Xoay chậu cho cây mọc đều',
            pestSusceptibility: 'Thối củ nếu úng'
          },
          {
            stageName: 'Trưởng thành',
            order: 3,
            duration: 365,
            description: 'Cây đạt kích thước lớn trong chậu, ít khi ra hoa.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 30,
            optimalHumidityMax: 70,
            optimalPHMin: 6.0,
            optimalPHMax: 7.0,
            optimalLightMin: 0,
            optimalLightMax: 2,
            lightRequirement: 'Trong nhà thiếu sáng vẫn sống tốt',
            waterRequirement: 'Rất thấp (quên tưới lâu cây vẫn OK)',
            nutrientRequirement: 'Thấp (ít cần bón phân)',
            careInstructions: 'Thay chậu 2–3 năm/lần',
            pestSusceptibility: 'Hiếm sâu bệnh'
          }
        ]
      }
    },
    {
      name: 'Cây Sen đá',
      scientificName: 'Echeveria spp.',
      family: 'Crassulaceae',
      description: 'Cây mọng nước nhỏ, lá dày xếp thành hình hoa sen, ưa nắng.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Nhân giống',
            order: 1,
            duration: 31,
            description: 'Giâm lá hoặc tách cây con để mọc chồi mới.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 30,
            optimalHumidityMax: 60,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 4,
            optimalLightMax: 8,
            lightRequirement: 'Nắng trực tiếp 4–6 giờ/ngày',
            waterRequirement: 'Thấp (chỉ tưới khi đất khô)',
            nutrientRequirement: 'Thấp (bón xương rồng 1 lần/năm)',
            careInstructions: 'Tránh nước đọng trên lá',
            pestSusceptibility: 'Thối gốc nếu úng'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 365,
            description: 'Cây phát triển chồi và lá mới, thân cao hơn.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 38,
            optimalHumidityMin: 30,
            optimalHumidityMax: 60,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 4,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều và thoáng khí',
            waterRequirement: 'Thấp (1–2 tuần tưới 1 lần)',
            nutrientRequirement: 'Thấp (bón hữu cơ 6 tháng/lần)',
            careInstructions: 'Loại bỏ lá khô héo',
            pestSusceptibility: 'Ít sâu bệnh'
          },
          {
            stageName: 'Ra hoa',
            order: 3,
            duration: 21,
            description: 'Cây có thể trổ hoa nhỏ màu rực rỡ.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 30,
            optimalHumidityMax: 60,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 6,
            optimalLightMax: 8,
            lightRequirement: 'Nắng mạnh kích thích ra hoa',
            waterRequirement: 'Thấp (giảm tưới khi có hoa)',
            nutrientRequirement: 'Thấp (bón kali thúc hoa)',
            careInstructions: 'Cắt bỏ cuống hoa khi tàn',
            pestSusceptibility: 'Ít sâu bệnh'
          }
        ]
      }
    },
    {
      name: 'Cây Xương rồng',
      scientificName: 'Opuntia microdasys',
      family: 'Cactaceae',
      description: 'Cây mọng nước thân gai, chịu hạn tốt, thường trồng chậu cảnh.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Nhân giống',
            order: 1,
            duration: 42,
            description: 'Gieo hạt hoặc giâm nhánh/bẹ trong đất cát ẩm để ra rễ.',
            optimalTemperatureMin: 22,
            optimalTemperatureMax: 40,
            optimalHumidityMin: 20,
            optimalHumidityMax: 50,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 6,
            optimalLightMax: 10,
            lightRequirement: 'Nắng gắt trực tiếp',
            waterRequirement: 'Rất thấp (1 tháng tưới 1 lần)',
            nutrientRequirement: 'Rất thấp (hầu như không bón)',
            careInstructions: 'Chậu phải thoát nước tốt',
            pestSusceptibility: 'Thối gốc nếu úng'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 365,
            description: 'Cây phát triển chậm, mọc thêm chồi hoặc nhánh.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 40,
            optimalHumidityMin: 20,
            optimalHumidityMax: 60,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 6,
            optimalLightMax: 10,
            lightRequirement: 'Nắng nhiều',
            waterRequirement: 'Rất thấp (đất khô mới tưới)',
            nutrientRequirement: 'Rất thấp',
            careInstructions: 'Xoay chậu đều để nhận nắng',
            pestSusceptibility: 'Ít sâu bệnh'
          },
          {
            stageName: 'Ra hoa',
            order: 3,
            duration: 10,
            description: 'Một số loài nở hoa rực rỡ khi đủ tuổi và nắng.',
            optimalTemperatureMin: 25,
            optimalTemperatureMax: 38,
            optimalHumidityMin: 20,
            optimalHumidityMax: 50,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 8,
            optimalLightMax: 10,
            lightRequirement: 'Nắng gắt liên tục',
            waterRequirement: 'Rất thấp',
            nutrientRequirement: 'Thấp (thêm photpho nếu cần)',
            careInstructions: 'Tránh mưa vào hoa',
            pestSusceptibility: 'Ít bị côn trùng'
          }
        ]
      }
    },
    {
      name: 'Cây Cau Tiểu Trâm',
      scientificName: 'Chamaedorea elegans',
      family: 'Arecaceae',
      description: 'Cây cọ lá lông chim xanh mượt, thích hợp trồng trong nhà, chịu bóng tốt.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Nhân giống',
            order: 1,
            duration: 49,
            description: 'Gieo hạt hoặc tách bụi cây con từ gốc mẹ.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 32,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 5.5,
            optimalPHMax: 7.5,
            optimalLightMin: 0,
            optimalLightMax: 2,
            lightRequirement: 'Bóng râm hoặc ánh sáng khuếch tán',
            waterRequirement: 'Trung bình (2 lần/tuần)',
            nutrientRequirement: 'Thấp (NPK loãng 3 tháng/lần)',
            careInstructions: 'Phun sương lên lá để tăng ẩm',
            pestSusceptibility: 'Nhện đỏ'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 365,
            description: 'Cây đâm nhiều lá mới, tán rộng cao 30–60cm.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 34,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 5.5,
            optimalPHMax: 7.5,
            optimalLightMin: 0,
            optimalLightMax: 2,
            lightRequirement: 'Ánh sáng gián tiếp',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Xoay chậu để cây mọc thẳng',
            pestSusceptibility: 'Rệp sáp'
          },
          {
            stageName: 'Trưởng thành',
            order: 3,
            duration: 365,
            description: 'Cây đạt kích thước chậu tối đa, thỉnh thoảng ra hoa và quả nhỏ.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 34,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 5.5,
            optimalPHMax: 7.5,
            optimalLightMin: 0,
            optimalLightMax: 2,
            lightRequirement: 'Bóng râm sâu',
            waterRequirement: 'Trung bình (giảm mùa lạnh)',
            nutrientRequirement: 'Thấp (1–2 lần/năm)',
            careInstructions: 'Thay chậu 2–3 năm/lần',
            pestSusceptibility: 'Ít sâu bệnh'
          }
        ]
      }
    },
    {
      name: 'Cây Dương xỉ',
      scientificName: 'Nephrolepis exaltata',
      family: 'Nephrolepidaceae',
      description: 'Cây thân thảo mọc thành bụi, lá lông chim xanh non, ưa ẩm và bóng râm.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Nhân giống',
            order: 1,
            duration: 18,
            description: 'Tách bụi cây con hoặc ươm bào tử (chậm).',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 28,
            optimalHumidityMin: 60,
            optimalHumidityMax: 90,
            optimalPHMin: 5.0,
            optimalPHMax: 7.0,
            optimalLightMin: 0,
            optimalLightMax: 1,
            lightRequirement: 'Bóng râm hoàn toàn',
            waterRequirement: 'Cao (đất luôn ẩm)',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Phun sương hàng ngày',
            pestSusceptibility: 'Ít sâu bệnh'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 365,
            description: 'Khóm lớn, lá dài 50–60cm, rũ xuống.',
            optimalTemperatureMin: 15,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 60,
            optimalHumidityMax: 90,
            optimalPHMin: 5.0,
            optimalPHMax: 7.0,
            optimalLightMin: 0,
            optimalLightMax: 1,
            lightRequirement: 'Râm mát',
            waterRequirement: 'Cao (3–4 lần/tuần)',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Tỉa lá già',
            pestSusceptibility: 'Ít bệnh'
          },
          {
            stageName: 'Trưởng thành',
            order: 3,
            duration: 365,
            description: 'Khóm dầy, lá dài và nhiều, có bào tử dưới mặt lá.',
            optimalTemperatureMin: 15,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 60,
            optimalHumidityMax: 90,
            optimalPHMin: 5.0,
            optimalPHMax: 7.0,
            optimalLightMin: 0,
            optimalLightMax: 1,
            lightRequirement: 'Bóng râm',
            waterRequirement: 'Cao',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Thay chậu 2 năm/lần',
            pestSusceptibility: 'Ít sâu bệnh'
          }
        ]
      }
    },
    {
      name: 'Cây Nha đam',
      scientificName: 'Aloe vera',
      family: 'Asphodelaceae',
      description: 'Cây mọng nước thân thảo, lá dày chứa gel, dùng làm dược liệu và làm đẹp.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Nhân giống',
            order: 1,
            duration: 18,
            description: 'Tách chồi con và trồng trong đất thoát nước tốt.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 30,
            optimalHumidityMax: 70,
            optimalPHMin: 6.0,
            optimalPHMax: 8.0,
            optimalLightMin: 4,
            optimalLightMax: 8,
            lightRequirement: 'Nắng sáng 4–6 giờ/ngày',
            waterRequirement: 'Thấp (1–2 tuần tưới 1 lần)',
            nutrientRequirement: 'Thấp (bón hữu cơ 4–6 tháng/lần)',
            careInstructions: 'Tránh nước đọng nách lá',
            pestSusceptibility: 'Thối gốc nếu úng'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 365,
            description: 'Cây lớn dần, lá dày mọc thêm chồi con quanh gốc.',
            optimalTemperatureMin: 15,
            optimalTemperatureMax: 40,
            optimalHumidityMin: 30,
            optimalHumidityMax: 70,
            optimalPHMin: 6.0,
            optimalPHMax: 8.0,
            optimalLightMin: 4,
            optimalLightMax: 8,
            lightRequirement: 'Ánh sáng đầy đủ',
            waterRequirement: 'Thấp (mùa mưa ít tưới)',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Tách chồi con khi chậu chật',
            pestSusceptibility: 'Ít sâu bệnh'
          },
          {
            stageName: 'Ra hoa',
            order: 3,
            duration: 28,
            description: 'Cây trổ cành hoa vàng/đỏ khi đủ tuổi.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 30,
            optimalHumidityMax: 70,
            optimalPHMin: 6.0,
            optimalPHMax: 8.0,
            optimalLightMin: 6,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều',
            waterRequirement: 'Thấp (giảm tưới khi ra hoa)',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Cắt bỏ cán hoa khi tàn',
            pestSusceptibility: 'Ít côn trùng'
          }
        ]
      }
    },
    {
      name: 'Cây Phú Quý',
      scientificName: 'Aglaonema sp.',
      family: 'Araceae',
      description: 'Cây cảnh lá pha đỏ/hồng, ưa bóng, phong thủy tài lộc.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Nhân giống',
            order: 1,
            duration: 35,
            description: 'Tách bụi hoặc giâm thân trong đất ẩm.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 5.5,
            optimalPHMax: 7.0,
            optimalLightMin: 0,
            optimalLightMax: 2,
            lightRequirement: 'Ánh sáng gián tiếp',
            waterRequirement: 'Trung bình (1–2 lần/tuần)',
            nutrientRequirement: 'Trung bình (2 tháng/lần)',
            careInstructions: 'Phun sương; lau lá',
            pestSusceptibility: 'Rệp sáp'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 365,
            description: 'Cây đâm thêm chồi, lá rực rỡ hơn.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 32,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 5.5,
            optimalPHMax: 7.0,
            optimalLightMin: 0,
            optimalLightMax: 2,
            lightRequirement: 'Ít ánh sáng vẫn sống',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Trung bình',
            careInstructions: 'Xoay chậu đều',
            pestSusceptibility: 'Nấm đốm lá'
          },
          {
            stageName: 'Trưởng thành',
            order: 3,
            duration: 365,
            description: 'Bụi dày, thỉnh thoảng ra hoa và quả.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 32,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 5.5,
            optimalPHMax: 7.0,
            optimalLightMin: 0,
            optimalLightMax: 2,
            lightRequirement: 'Ánh sáng khuếch tán',
            waterRequirement: 'Trung bình (giảm mùa lạnh)',
            nutrientRequirement: 'Thấp (6 tháng/lần)',
            careInstructions: 'Thay chậu 2 năm/lần',
            pestSusceptibility: 'Ít sâu bệnh'
          }
        ]
      }
    },
    {
      name: 'Cây Hương thảo',
      scientificName: 'Rosmarinus officinalis',
      family: 'Lamiaceae',
      description: 'Cây gia vị lá kim nhỏ thơm nồng, ưa nắng và khô ráo.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Nhân giống',
            order: 1,
            duration: 42,
            description: 'Giâm cành bánh tẻ trong đất ẩm.',
            optimalTemperatureMin: 15,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 30,
            optimalHumidityMax: 60,
            optimalPHMin: 6.5,
            optimalPHMax: 7.5,
            optimalLightMin: 5,
            optimalLightMax: 8,
            lightRequirement: 'Nắng trực tiếp 5–6 giờ/ngày',
            waterRequirement: 'Thấp (đất khô mới tưới)',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Tỉa cành để phân nhánh',
            pestSusceptibility: 'Thối gốc nếu ẩm'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 365,
            description: 'Cây phát triển thành bụi cao 30–60cm.',
            optimalTemperatureMin: 10,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 30,
            optimalHumidityMax: 70,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 5,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều, thoáng gió',
            waterRequirement: 'Thấp (1–2 lần/tuần)',
            nutrientRequirement: 'Thấp (6 tháng/lần)',
            careInstructions: 'Chậu phải thoát nước',
            pestSusceptibility: 'Ít sâu bệnh'
          },
          {
            stageName: 'Ra hoa',
            order: 3,
            duration: 21,
            description: 'Hoa tím nhạt nhỏ, thu hút ong bướm.',
            optimalTemperatureMin: 15,
            optimalTemperatureMax: 25,
            optimalHumidityMin: 30,
            optimalHumidityMax: 60,
            optimalPHMin: 6.5,
            optimalPHMax: 7.5,
            optimalLightMin: 5,
            optimalLightMax: 8,
            lightRequirement: 'Ánh sáng dịu buổi sáng/chiều',
            waterRequirement: 'Thấp (giảm tưới)',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Cắt tỉa hoa sau tàn',
            pestSusceptibility: 'Ít sâu bệnh'
          }
        ]
      }
    },
    {
      name: 'Cây Bạc hà',
      scientificName: 'Mentha arvensis',
      family: 'Lamiaceae',
      description: 'Cây thân thảo bò, lá nhỏ the mát, dùng làm rau gia vị và trà.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Nhân giống',
            order: 1,
            duration: 10,
            description: 'Giâm cành hoặc tách khóm rễ trong đất ẩm.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 3,
            optimalLightMax: 6,
            lightRequirement: 'Nắng sáng buổi sáng, bán râm chiều',
            waterRequirement: 'Cao (3–4 lần/tuần)',
            nutrientRequirement: 'Trung bình',
            careInstructions: 'Cắt tỉa ngọn để phân nhánh',
            pestSusceptibility: 'Rệp, sâu'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 365,
            description: 'Cây lan tỏa, đâm chồi mới quanh khóm.',
            optimalTemperatureMin: 15,
            optimalTemperatureMax: 37,
            optimalHumidityMin: 50,
            optimalHumidityMax: 90,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 3,
            optimalLightMax: 6,
            lightRequirement: 'Ánh sáng một phần',
            waterRequirement: 'Cao',
            nutrientRequirement: 'Trung bình',
            careInstructions: 'Cắt bỏ hoa để tập trung lá',
            pestSusceptibility: 'Ít bệnh'
          },
          {
            stageName: 'Thu hoạch',
            order: 3,
            duration: 365,
            description: 'Ngắt lá hoặc cắt ngọn liên tục khi khóm xanh tốt.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 3,
            optimalLightMax: 6,
            lightRequirement: 'Nắng nhẹ để phục hồi',
            waterRequirement: 'Cao',
            nutrientRequirement: 'Trung bình',
            careInstructions: 'Thu hoạch so le để khóm còn chồi',
            pestSusceptibility: 'Ít bệnh'
          }
        ]
      }
    },
    {
      name: 'Cây Húng quế',
      scientificName: 'Ocimum basilicum',
      family: 'Lamiaceae',
      description: 'Cây rau gia vị, lá xanh thơm hăng, ăn kèm phở, bún.',
      growthDuration: 120,
      growthStages: {
        create: [
          {
            stageName: 'Gieo hạt',
            order: 1,
            duration: 6,
            description: 'Gieo hạt trên đất ẩm, che chắn nhẹ.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.0,
            optimalLightMin: 4,
            optimalLightMax: 8,
            lightRequirement: 'Ánh sáng đầy đủ',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Che chắn nhẹ giữ ẩm',
            pestSusceptibility: 'Nấm mốc'
          },
          {
            stageName: 'Cây con',
            order: 2,
            duration: 18,
            description: 'Cây cao 5–10cm, ra 2–3 cặp lá thật.',
            optimalTemperatureMin: 22,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.0,
            optimalLightMin: 6,
            optimalLightMax: 8,
            lightRequirement: 'Nắng sáng',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Trung bình',
            careInstructions: 'Ngắt ngọn lần đầu',
            pestSusceptibility: 'Sâu ăn lá'
          },
          {
            stageName: 'Sinh trưởng',
            order: 3,
            duration: 35,
            description: 'Cây thành bụi nhỏ cao 20–30cm.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 6,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Cao (2 tuần/bón)',
            careInstructions: 'Ngắt đọt thường xuyên',
            pestSusceptibility: 'Rệp muội'
          },
          {
            stageName: 'Ra hoa',
            order: 4,
            duration: 21,
            description: 'Cây trổ hoa tím nhạt nếu không ngắt ngọn.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 40,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 6,
            optimalLightMax: 8,
            lightRequirement: 'Ánh sáng đầy đủ',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Ngắt hoa sớm để tập trung lá',
            pestSusceptibility: 'Ít sâu bệnh'
          },
          {
            stageName: 'Thu hoạch',
            order: 5,
            duration: 365,
            description: 'Ngắt lá hoặc cắt cành từ 40–50 ngày tuổi, thu nhiều đợt.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 5,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhẹ',
            waterRequirement: 'Cao',
            nutrientRequirement: 'Cao (sau thu hoạch)',
            careInstructions: 'Thu hoạch sáng sớm',
            pestSusceptibility: 'Rệp muội'
          }
        ]
      }
    },
    {
      name: 'Cây Ngò rí',
      scientificName: 'Coriandrum sativum',
      family: 'Apiaceae',
      description: 'Cây rau mùi, lá xẻ thùy, mùi thơm dễ chịu, gia vị và trang trí.',
      growthDuration: 60,
      growthStages: {
        create: [
          {
            stageName: 'Gieo hạt',
            order: 1,
            duration: 10,
            description: 'Ngâm hạt ấm, gieo trên đất ẩm, che nhẹ.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 50,
            optimalHumidityMax: 70,
            optimalPHMin: 6.0,
            optimalPHMax: 7.0,
            optimalLightMin: 4,
            optimalLightMax: 6,
            lightRequirement: 'Ánh sáng nhẹ',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Phủ rơm giữ ẩm',
            pestSusceptibility: 'Chim kiến'
          },
          {
            stageName: 'Cây con',
            order: 2,
            duration: 18,
            description: 'Cây cao 5–7cm, lá mầm và lá thật nhỏ xuất hiện.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 50,
            optimalHumidityMax: 70,
            optimalPHMin: 6.0,
            optimalPHMax: 7.0,
            optimalLightMin: 4,
            optimalLightMax: 6,
            lightRequirement: 'Ánh sáng buổi sáng',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Tỉa bớt cây dày',
            pestSusceptibility: 'Thối nhũn nếu úng'
          },
          {
            stageName: 'Sinh trưởng',
            order: 3,
            duration: 28,
            description: 'Cây cao 15–30cm, thu hoạch lá ngọn.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 4,
            optimalLightMax: 6,
            lightRequirement: 'Ánh sáng sáng buổi sáng',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Trung bình',
            careInstructions: 'Ngắt đọt thường xuyên',
            pestSusceptibility: 'Rệp muội'
          },
          {
            stageName: 'Ra hoa & tạo hạt',
            order: 4,
            duration: 21,
            description: 'Cây trổ tán hoa trắng nhỏ, kết hạt rồi lá già cứng và kém thơm.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 40,
            optimalHumidityMax: 70,
            optimalPHMin: 6.0,
            optimalPHMax: 7.0,
            optimalLightMin: 6,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều',
            waterRequirement: 'Thấp',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Thu hạt khô làm giống',
            pestSusceptibility: 'Ít sâu bệnh'
          }
        ]
      }
    },
    {
      name: 'Cây Ngò gai',
      scientificName: 'Eryngium foetidum',
      family: 'Apiaceae',
      description: 'Cây rau thơm lá thon có răng cưa, mùi đậm, dùng nêm phở, canh chua.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Gieo hạt',
            order: 1,
            duration: 12,
            description: 'Giữ ấm và ẩm để hạt nảy mầm sau ~2 tuần.',
            optimalTemperatureMin: 22,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 60,
            optimalHumidityMax: 90,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 2,
            optimalLightMax: 5,
            lightRequirement: 'Bán râm',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Che phủ rơm giữ ẩm',
            pestSusceptibility: 'Thối hạt nếu úng'
          },
          {
            stageName: 'Cây con',
            order: 2,
            duration: 25,
            description: 'Cây mọc lá ngắn, thân thấp.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 60,
            optimalHumidityMax: 90,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 3,
            optimalLightMax: 6,
            lightRequirement: 'Bán râm',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Tỉa cây yếu',
            pestSusceptibility: 'Ốc sên'
          },
          {
            stageName: 'Sinh trưởng',
            order: 3,
            duration: 90,
            description: 'Cây ra lá dài 10–20cm, thu hoạch lá thường xuyên.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 60,
            optimalHumidityMax: 90,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 3,
            optimalLightMax: 6,
            lightRequirement: 'Bán phần',
            waterRequirement: 'Cao',
            nutrientRequirement: 'Trung bình',
            careInstructions: 'Phủ rơm giữ ẩm',
            pestSusceptibility: 'Ốc sên'
          },
          {
            stageName: 'Ra hoa & tái sinh',
            order: 4,
            duration: 180,
            description: 'Cây trổ hoa gai xanh, rụng hạt nảy cây mới.',
            optimalTemperatureMin: 22,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 4,
            optimalLightMax: 6,
            lightRequirement: 'Ánh sáng nhiều',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Thu hạt làm giống',
            pestSusceptibility: 'Ốc sên'
          }
        ]
      }
    },
    {
      name: 'Cây Tía tô',
      scientificName: 'Perilla frutescens',
      family: 'Lamiaceae',
      description: 'Cây rau thơm lá tím, vị hăng, ăn sống và nấu cháo.',
      growthDuration: 80,
      growthStages: {
        create: [
          {
            stageName: 'Gieo hạt',
            order: 1,
            duration: 8,
            description: 'Ngâm hạt, gieo đất ẩm, che chắn.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 4,
            optimalLightMax: 6,
            lightRequirement: 'Ánh sáng vừa phải',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Che chắn nhẹ',
            pestSusceptibility: 'Sâu ăn lá'
          },
          {
            stageName: 'Cây con',
            order: 2,
            duration: 18,
            description: 'Cây cao 5–10cm, có lá tím.',
            optimalTemperatureMin: 22,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 4,
            optimalLightMax: 6,
            lightRequirement: 'Ánh sáng sáng buổi sáng',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Trung bình',
            careInstructions: 'Bấm ngọn kích thải nhánh',
            pestSusceptibility: 'Sâu xanh'
          },
          {
            stageName: 'Sinh trưởng',
            order: 3,
            duration: 35,
            description: 'Cây thành bụi cao 30–50cm, thu hoạch lá ngọn.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 50,
            optimalHumidityMax: 85,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 5,
            optimalLightMax: 7,
            lightRequirement: 'Bán râm hoặc nắng nhẹ',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Trung bình',
            careInstructions: 'Thu hoạch lá thường xuyên',
            pestSusceptibility: 'Sâu khoang'
          },
          {
            stageName: 'Ra hoa & thu hạt',
            order: 4,
            duration: 21,
            description: 'Cây trổ hoa trắng tím, kết hạt, lá già cứng.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 40,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 6,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều',
            waterRequirement: 'Thấp',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Thu hạt phơi khô',
            pestSusceptibility: 'Ít sâu bệnh'
          }
        ]
      }
    },
    {
      name: 'Cây Hành lá',
      scientificName: 'Allium fistulosum',
      family: 'Amaryllidaceae',
      description: 'Rau gia vị thân ống xanh, trắng gốc, thơm nhẹ, nêm canh.',
      growthDuration: 60,
      growthStages: {
        create: [
          {
            stageName: 'Gieo trồng',
            order: 1,
            duration: 10,
            description: 'Gieo hạt hoặc trồng gốc hành có rễ, nảy mầm sau 1 tuần.',
            optimalTemperatureMin: 15,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.0,
            optimalLightMin: 5,
            optimalLightMax: 8,
            lightRequirement: 'Nắng sáng cả ngày',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Phủ đất mỏng giữ ẩm',
            pestSusceptibility: 'Sâu ăn lá'
          },
          {
            stageName: 'Cây con',
            order: 2,
            duration: 18,
            description: 'Hành cao 5–10cm, cần tỉa thưa.',
            optimalTemperatureMin: 15,
            optimalTemperatureMax: 32,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.0,
            optimalLightMin: 5,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Trung bình',
            careInstructions: 'Vun gốc giúp cây đứng',
            pestSusceptibility: 'Thối nhũn gốc'
          },
          {
            stageName: 'Sinh trưởng',
            order: 3,
            duration: 45,
            description: 'Cây cao 30–40cm, có thể thu hoạch lá hoặc nhổ gốc.',
            optimalTemperatureMin: 15,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 50,
            optimalHumidityMax: 85,
            optimalPHMin: 6.0,
            optimalPHMax: 7.0,
            optimalLightMin: 6,
            optimalLightMax: 8,
            lightRequirement: 'Nắng đầy đủ',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Cao (sau mỗi cắt lá)',
            careInstructions: 'Thu hoạch tỉa lá giữ cây xanh',
            pestSusceptibility: 'Sâu đục thân'
          },
          {
            stageName: 'Thu hoạch',
            order: 4,
            duration: 365,
            description: 'Cắt lá hoặc nhổ cả củ, có thể tái sinh sau cắt lá.',
            optimalTemperatureMin: 15,
            optimalTemperatureMax: 30,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 6.0,
            optimalPHMax: 7.0,
            optimalLightMin: 5,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều',
            waterRequirement: 'Cao',
            nutrientRequirement: 'Cao',
            careInstructions: 'Bón đạm sau thu hoạch',
            pestSusceptibility: 'Nấm gốc'
          }
        ]
      }
    },
    {
      name: 'Cây Sả',
      scientificName: 'Cymbopogon citratus',
      family: 'Poaceae',
      description: 'Cỏ lưu niên thơm chanh, dùng nêm ướp, xua muỗi.',
      growthDuration: null,
      growthStages: {
        create: [
          {
            stageName: 'Trồng hom',
            order: 1,
            duration: 21,
            description: 'Trồng đoạn gốc sả tươi có rễ xuống đất ẩm.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 50,
            optimalHumidityMax: 90,
            optimalPHMin: 5.5,
            optimalPHMax: 7.5,
            optimalLightMin: 5,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Vun gốc, phủ rơm giữ ẩm',
            pestSusceptibility: 'Ít sâu bệnh'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 120,
            description: 'Khóm đẻ nhánh, lá dài, thu hoạch sau 3–6 tháng.',
            optimalTemperatureMin: 18,
            optimalTemperatureMax: 37,
            optimalHumidityMin: 50,
            optimalHumidityMax: 90,
            optimalPHMin: 5.5,
            optimalPHMax: 7.5,
            optimalLightMin: 5,
            optimalLightMax: 8,
            lightRequirement: 'Nắng mạnh',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Trung bình',
            careInstructions: 'Vun gốc, cắt bớt lá già',
            pestSusceptibility: 'Hiếm'
          },
          {
            stageName: 'Thu hoạch',
            order: 3,
            duration: 365,
            description: 'Tách nhánh sả khi gốc đủ to, khóm tiếp tục đẻ nhánh.',
            optimalTemperatureMin: 20,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 50,
            optimalHumidityMax: 80,
            optimalPHMin: 5.5,
            optimalPHMax: 7.5,
            optimalLightMin: 5,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Trung bình',
            careInstructions: 'Thu hoạch xen kẽ, bón phân sau mỗi lần',
            pestSusceptibility: 'Ít bệnh'
          }
        ]
      }
    },
    {
      name: 'Rau muống',
      scientificName: 'Ipomoea aquatica',
      family: 'Convolvulaceae',
      description: 'Rau ăn lá, thân rỗng ưa nước, xào tỏi, nấu canh.',
      growthDuration: 40,
      growthStages: {
        create: [
          {
            stageName: 'Gieo hom',
            order: 1,
            duration: 6,
            description: 'Giâm hom xuống đất ngập nước hoặc bùn lầy.',
            optimalTemperatureMin: 25,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 70,
            optimalHumidityMax: 100,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 6,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều',
            waterRequirement: 'Rất cao (ngập nước)',
            nutrientRequirement: 'Cao',
            careInstructions: 'Giữ mực nước 5–10cm',
            pestSusceptibility: 'Ốc bưu'
          },
          {
            stageName: 'Sinh trưởng',
            order: 2,
            duration: 25,
            description: 'Rau phát triển nhanh, dây lan khắp mặt nước.',
            optimalTemperatureMin: 25,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 70,
            optimalHumidityMax: 100,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 6,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều',
            waterRequirement: 'Rất cao',
            nutrientRequirement: 'Cao',
            careInstructions: 'Bón chuồng hoai',
            pestSusceptibility: 'Sâu khoang'
          },
          {
            stageName: 'Thu hoạch',
            order: 3,
            duration: 365,
            description: 'Cắt khi dây dài 30–40cm, chừa gốc 5cm.',
            optimalTemperatureMin: 25,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 70,
            optimalHumidityMax: 100,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 5,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều',
            waterRequirement: 'Rất cao',
            nutrientRequirement: 'Cao',
            careInstructions: 'Thu hoạch luân phiên',
            pestSusceptibility: 'Rêu tảo'
          }
        ]
      }
    },
    {
      name: 'Rau mồng tơi',
      scientificName: 'Basella alba',
      family: 'Basellaceae',
      description: 'Rau leo, lá nhớt, nấu canh hoặc luộc, tính mát.',
      growthDuration: 50,
      growthStages: {
        create: [
          {
            stageName: 'Gieo hạt',
            order: 1,
            duration: 8,
            description: 'Ngâm hạt rồi gieo, giữ ẩm đất.',
            optimalTemperatureMin: 25,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 70,
            optimalHumidityMax: 100,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 5,
            optimalLightMax: 8,
            lightRequirement: 'Nắng nhiều',
            waterRequirement: 'Trung bình',
            nutrientRequirement: 'Thấp',
            careInstructions: 'Phủ rơm giữ ẩm',
            pestSusceptibility: 'Sên'
          },
          {
            stageName: 'Cây con',
            order: 2,
            duration: 18,
            description: 'Cây cao ~15cm, bắt đầu leo giàn.',
            optimalTemperatureMin: 25,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 60,
            optimalHumidityMax: 100,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 4,
            optimalLightMax: 8,
            lightRequirement: 'Ánh sáng sáng buổi sáng',
            waterRequirement: 'Cao',
            nutrientRequirement: 'Cao',
            careInstructions: 'Cắm giàn leo',
            pestSusceptibility: 'Sâu ăn lá'
          },
          {
            stageName: 'Sinh trưởng',
            order: 3,
            duration: 45,
            description: 'Dây leo phủ giàn, lá mọc dày.',
            optimalTemperatureMin: 25,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 70,
            optimalHumidityMax: 100,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 6,
            optimalLightMax: 8,
            lightRequirement: 'Nắng sáng',
            waterRequirement: 'Cao',
            nutrientRequirement: 'Cao',
            careInstructions: 'Thu hoạch ngọn non',
            pestSusceptibility: 'Sâu ăn lá'
          },
          {
            stageName: 'Thu hoạch',
            order: 4,
            duration: 365,
            description: 'Cắt ngọn dài 20–30cm, chừa lại gốc.',
            optimalTemperatureMin: 25,
            optimalTemperatureMax: 35,
            optimalHumidityMin: 70,
            optimalHumidityMax: 100,
            optimalPHMin: 6.0,
            optimalPHMax: 7.5,
            optimalLightMin: 5,
            optimalLightMax: 8,
            lightRequirement: 'Nắng sáng',
            waterRequirement: 'Cao',
            nutrientRequirement: 'Cao',
            careInstructions: 'Luân phiên cắt từng dây',
            pestSusceptibility: 'Rệp sáp'
          }
        ]
      }
    }
  ];

  for (const pt of plantTypes) {
    await prisma.plantType.upsert({
      where: { name: pt.name },
      update: {},
      create: {
        name: pt.name,
        scientificName: pt.scientificName,
        family: pt.family,
        description: pt.description,
        growthDuration: pt.growthDuration,
        growthStages: pt.growthStages
      }
    });
  }

  console.log('✅ Seed 30 loại cây thành công.');
}
